--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-04-20 03:43:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 19931)
-- Name: transport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transport (
    id integer NOT NULL,
    nrlinie character varying(255),
    nrstatie integer NOT NULL,
    statie character varying(255)
);


ALTER TABLE public.transport OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 19930)
-- Name: transport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 19939)
-- Name: utilizator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilizator (
    id integer NOT NULL,
    cnp character varying(255),
    mail character varying(255),
    numartelefon character varying(255),
    nume character varying(255),
    parola character varying(255),
    prenume character varying(255),
    tip character varying(255),
    username character varying(255)
);


ALTER TABLE public.utilizator OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 19938)
-- Name: utilizator_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilizator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilizator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3325 (class 0 OID 19931)
-- Dependencies: 215
-- Data for Name: transport; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (4, '23b', 1, 'Lalele');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (5, '23b', 1, 'Lalele');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (6, '23b', 1, 'Lalele');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (7, '23b', 1, 'Lalele');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (8, '23b', 0, 'Lalele');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (9, '23b', 2, 'Lalele');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (3, '25', 2, 'paltinisi');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (16, '3', 3, '4');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (20, '34', 1, 'sdc');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (21, '1', 1, 'A');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (23, '1', 2, 'B');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (24, '1', 3, 'D');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (26, '1', 4, 'E');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (28, '2', 1, 'D');
INSERT INTO public.transport (id, nrlinie, nrstatie, statie) VALUES (29, '2', 2, 'F');


--
-- TOC entry 3327 (class 0 OID 19939)
-- Dependencies: 217
-- Data for Name: utilizator; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.utilizator (id, cnp, mail, numartelefon, nume, parola, prenume, tip, username) VALUES (10, 'dasada', 'dasdada@F', NULL, NULL, 'Dsadas', NULL, 'angajat', NULL);
INSERT INTO public.utilizator (id, cnp, mail, numartelefon, nume, parola, prenume, tip, username) VALUES (11, 'dasada', 'dasdada@F', NULL, NULL, 'delfin', NULL, 'angajat', 'delfin');
INSERT INTO public.utilizator (id, cnp, mail, numartelefon, nume, parola, prenume, tip, username) VALUES (12, 'dasada', 'dasdada@F', NULL, NULL, 'Plutoniu', NULL, 'manager', 'Plutoniu');


--
-- TOC entry 3333 (class 0 OID 0)
-- Dependencies: 214
-- Name: transport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transport_id_seq', 29, true);


--
-- TOC entry 3334 (class 0 OID 0)
-- Dependencies: 216
-- Name: utilizator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utilizator_id_seq', 15, true);


--
-- TOC entry 3179 (class 2606 OID 19937)
-- Name: transport transport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT transport_pkey PRIMARY KEY (id);


--
-- TOC entry 3181 (class 2606 OID 19945)
-- Name: utilizator utilizator_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilizator
    ADD CONSTRAINT utilizator_pkey PRIMARY KEY (id);


-- Completed on 2023-04-20 03:43:50

--
-- PostgreSQL database dump complete
--

